# Generated by Django 5.2.7 on 2025-12-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_home_country_profile_ip_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='recovery_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
