# Generated by Django 5.2.7 on 2025-12-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_avatar_profile_recovery_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
