# Generated by Django 5.2.7 on 2025-12-20 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_address_line_1_profile_address_line_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v1_email', models.BooleanField(default=False)),
                ('v2_phone', models.BooleanField(default=False)),
                ('v3_location', models.BooleanField(default=False)),
                ('v4_gender', models.BooleanField(default=False)),
                ('v5_age', models.BooleanField(default=False)),
                ('verification_video', models.FileField(blank=True, null=True, upload_to='verification_videos/')),
                ('v2_code', models.CharField(blank=True, max_length=6, null=True)),
                ('detected_gender', models.CharField(blank=True, max_length=20, null=True)),
                ('detected_age_range', models.CharField(blank=True, max_length=20, null=True)),
                ('ai_analysis_status', models.CharField(default='pending', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
