# Generated by Django 5.2.7 on 2025-12-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_verificationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationprofile',
            name='ai_analysis_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
