services:
  django-web:
    restart: always
    command: >
      ./entrypoint.sh
    env_file:
      - .env.prod
    volumes:
      - media_volume:/app/mediafiles
      - ./data:/app/data

  db:
    restart: always
    env_file:
      - .env.prod

  redis:
    restart: always

  qcluster:
    restart: always
    command: ./entrypoint.sh python manage.py qcluster
    env_file:
      - .env.prod
    volumes:
      - ./data:/app/data

volumes:
  media_volume:
