services:
  django-web:
    restart: always
    command: >
      daphne -b 0.0.0.0 -p 8000 klikdat_django.asgi:application
    volumes:
      - media_volume:/app/mediafiles

  db:
    restart: always

  redis:
    restart: always

volumes:
  media_volume:
