# Generated by Django 5.2.7 on 2025-12-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_creator_chatroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='module',
            field=models.CharField(blank=True, choices=[('matchmake', 'Matchmake'), ('vehicle', 'Vehicle'), ('recruitment', 'Recruitment'), ('property', 'Property')], max_length=20, null=True),
        ),
    ]
