# Generated by Django 5.2.7 on 2025-12-21 11:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_chatroom_creator_chatroom_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchmakeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='matchmake_intros/')),
                ('smoking', models.CharField(blank=True, choices=[('Never', 'Never'), ('Socially', 'Socially'), ('Regularly', 'Regularly')], max_length=20, null=True)),
                ('drinking', models.CharField(blank=True, choices=[('Never', 'Never'), ('Socially', 'Socially'), ('Regularly', 'Regularly')], max_length=20, null=True)),
                ('exercise', models.CharField(blank=True, choices=[('Never', 'Never'), ('Sometimes', 'Sometimes'), ('Active', 'Active'), ('Athletic', 'Athletic')], max_length=20, null=True)),
                ('dietary_preferences', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('relationship_goal', models.CharField(blank=True, choices=[('Long-term', 'Long-term relationship'), ('Casual', 'Casual dating'), ('Friendship', 'Friendship'), ('Not Sure', 'Not sure yet')], max_length=50, null=True)),
                ('pref_min_age', models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18)])),
                ('pref_max_age', models.IntegerField(default=99)),
                ('pref_max_distance', models.IntegerField(default=50, help_text='In kilometers')),
                ('pref_looking_for', models.CharField(default='Everyone', max_length=20)),
                ('interests', models.ManyToManyField(blank=True, to='matchmake.interest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matchmake_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchmakePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='matchmake_photos/')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='matchmake.matchmakeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_room', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chatroom')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('swiped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_received', to=settings.AUTH_USER_MODEL)),
                ('swiper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('swiper', 'swiped')},
            },
        ),
    ]
