# Generated by Django 5.2.7 on 2025-12-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmakeprofile',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matchmakeprofile',
            name='future_family_plans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matchmakeprofile',
            name='height',
            field=models.IntegerField(blank=True, help_text='In centimeters', null=True),
        ),
        migrations.AddField(
            model_name='matchmakeprofile',
            name='languages_spoken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matchmakeprofile',
            name='pets',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matchmakeprofile',
            name='politics',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matchmakeprofile',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matchmakeprofile',
            name='zodiac',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matchmakeprofile',
            name='relationship_goal',
            field=models.CharField(blank=True, choices=[('Long-term', 'Long-term relationship'), ('Short-term', 'Short-term relationship'), ('Casual', 'Casual dating'), ('Friendship', 'Friendship'), ('Not Sure', 'Not sure yet')], max_length=50, null=True),
        ),
    ]
