# Generated by Django 5.2.7 on 2025-12-01 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gearbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Gearboxes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SellerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vehicles.make')),
            ],
            options={
                'ordering': ['make__name', 'name'],
                'unique_together': {('name', 'make')},
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField(help_text='Mileage in kilometers')),
                ('location', models.CharField(max_length=200)),
                ('num_doors', models.IntegerField(blank=True, null=True)),
                ('num_seats', models.IntegerField(blank=True, null=True)),
                ('battery_range', models.IntegerField(blank=True, help_text='Range in kilometers', null=True)),
                ('charging_time', models.DecimalField(blank=True, decimal_places=2, help_text='Charging time in hours', max_digits=5, null=True)),
                ('engine_size', models.DecimalField(blank=True, decimal_places=2, help_text='Engine size in liters', max_digits=5, null=True)),
                ('engine_power', models.IntegerField(blank=True, help_text='Engine power in horsepower', null=True)),
                ('acceleration', models.DecimalField(blank=True, decimal_places=2, help_text='0-100 km/h in seconds', max_digits=5, null=True)),
                ('fuel_consumption', models.DecimalField(blank=True, decimal_places=2, help_text='Fuel consumption in L/100km', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.bodytype')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.color')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.fueltype')),
                ('gearbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.gearbox')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.model')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
                ('seller_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.sellertype')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehicletype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
