# Generated by Django 5.2.7 on 2025-12-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicleimage_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodytype',
            options={'ordering': ['body_type']},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['color']},
        ),
        migrations.AlterModelOptions(
            name='fueltype',
            options={'ordering': ['fuel_type']},
        ),
        migrations.AlterModelOptions(
            name='gearbox',
            options={'ordering': ['gearbox'], 'verbose_name_plural': 'Gearboxes'},
        ),
        migrations.AlterModelOptions(
            name='make',
            options={'ordering': ['make']},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['make__make', 'model']},
        ),
        migrations.AlterModelOptions(
            name='sellertype',
            options={'ordering': ['seller_type']},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'ordering': ['vehicle_type']},
        ),
        migrations.RenameField(
            model_name='bodytype',
            old_name='name',
            new_name='body_type',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='name',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='fueltype',
            old_name='name',
            new_name='fuel_type',
        ),
        migrations.RenameField(
            model_name='gearbox',
            old_name='name',
            new_name='gearbox',
        ),
        migrations.RenameField(
            model_name='make',
            old_name='name',
            new_name='make',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='name',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='sellertype',
            old_name='name',
            new_name='seller_type',
        ),
        migrations.RenameField(
            model_name='vehicletype',
            old_name='name',
            new_name='vehicle_type',
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together={('model', 'make')},
        ),
    ]
