# Generated by Django 5.2.7 on 2025-12-10 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_bodytype_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='schema',
            field=models.JSONField(blank=True, default=dict, help_text='JSON schema definition for dynamic attributes'),
        ),
        migrations.CreateModel(
            name='VehicleAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text="Unique key for this attribute (e.g. 'berth')", max_length=100, unique=True)),
                ('attribute_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select (Dropdown)'), ('boolean', 'Checkbox')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False, help_text='Is this attribute mandatory for the associated vehicle types?')),
                ('vehicle_types', models.ManyToManyField(blank=True, related_name='attributes', to='vehicles.vehicletype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Display label (e.g. '6x4')", max_length=100)),
                ('value', models.CharField(help_text="Stored value (e.g. '6x4')", max_length=100)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='vehicles.vehicleattribute')),
            ],
            options={
                'ordering': ['attribute', 'label'],
                'unique_together': {('attribute', 'value')},
            },
        ),
    ]
