# Generated by Django 5.2.7 on 2025-12-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_specifications_vehicletype_schema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='color',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='gearbox',
        ),
        migrations.DeleteModel(
            name='BodyType',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='FuelType',
        ),
        migrations.DeleteModel(
            name='Gearbox',
        ),
    ]
