# Generated by Django 5.2.7 on 2025-12-10 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_remove_vehicle_body_type_remove_vehicle_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='vehicle_types',
            field=models.ManyToManyField(related_name='makes', to='vehicles.vehicletype'),
        ),
        migrations.AddField(
            model_name='model',
            name='vehicle_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vehicles.vehicletype'),
        ),
    ]
