# Generated by Django 5.2.7 on 2025-12-10 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_make_vehicle_types_model_vehicle_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='Optional display name for listings', max_length=100)),
                ('contact_number', models.CharField(blank=True, help_text='Contact number for vehicle sales', max_length=20)),
                ('seller_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.sellertype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
