# Generated by Django 5.2.7 on 2025-12-10 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_vehicleprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='seller_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicles.sellertype'),
        ),
    ]
