# Generated by Django 5.2.7 on 2025-12-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_alter_vehicle_seller_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='boot_space',
            field=models.IntegerField(blank=True, help_text='Boot space in liters', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tax_per_year',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual tax amount', max_digits=10, null=True),
        ),
    ]
