# Generated by Django 5.2.7 on 2025-12-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_vehicle_boot_space_vehicle_tax_per_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the vehicle', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='title',
            field=models.CharField(blank=True, help_text='Short title/headline for the listing', max_length=200, null=True),
        ),
    ]
