# Generated by Django 5.2.7 on 2025-12-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_savedvehicle_delete_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL link to the video of the vehicle', null=True),
        ),
    ]
