# Generated by Django 5.2.7 on 2025-12-21 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('vehicles', '0015_sellerprofile_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='about_us',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='website',
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='business',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to='business.businessprofile'),
            preserve_default=False,
        ),
    ]
