# Generated by Django 5.2.7 on 2025-12-21 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('vehicles', '0017_vehicle_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='business.businessprofile'),
            preserve_default=False,
        ),
    ]
