# Generated by Django 5.2.7 on 2025-12-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpAsn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ip', models.GenericIPAddressField()),
                ('end_ip', models.GenericIPAddressField()),
                ('asn', models.IntegerField()),
                ('country_code', models.CharField(max_length=2)),
                ('organization', models.CharField(max_length=255)),
            ],
        ),
    ]
