# Generated by Django 5.2.7 on 2025-12-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipasn',
            name='asn',
            field=models.BigIntegerField(),
        ),
    ]
