# Generated by Django 5.2.7 on 2025-12-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_ipasn_asn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=2, null=True, unique=True)),
                ('geometry', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GadmBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('level', models.IntegerField(default=0)),
                ('parent_gid', models.CharField(blank=True, max_length=50, null=True)),
                ('geometry', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IpCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ip', models.GenericIPAddressField()),
                ('end_ip', models.GenericIPAddressField()),
                ('country_code', models.CharField(max_length=2)),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorldBankBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('iso_code', models.CharField(blank=True, max_length=3, null=True)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IsoRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('region_code', models.CharField(max_length=10)),
                ('region_name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('country_code', 'region_code')},
            },
        ),
    ]
