# Generated by Django 5.2.7 on 2025-12-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_continent_gadmboundary_ipcountry_worldbankboundary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryInfo',
            fields=[
                ('country_code', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('country_name', models.CharField(max_length=255)),
                ('country_alpha3_code', models.CharField(blank=True, max_length=3, null=True)),
                ('country_numeric_code', models.CharField(blank=True, max_length=10, null=True)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('country_demonym', models.CharField(blank=True, max_length=255, null=True)),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('idd_code', models.CharField(blank=True, max_length=10, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=3, null=True)),
                ('currency_name', models.CharField(blank=True, max_length=255, null=True)),
                ('currency_symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('lang_code', models.CharField(blank=True, max_length=10, null=True)),
                ('lang_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cctld', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='IpCountry',
        ),
    ]
