# Generated by Django 5.2.7 on 2025-12-19 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_countryinfo_delete_ipcountry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='isoregion',
            unique_together={('country_code', 'region_code', 'region_name')},
        ),
    ]
