# Generated by Django 5.2.7 on 2025-12-19 17:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_alter_isoregion_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continent',
            name='geometry',
        ),
        migrations.AddField(
            model_name='continent',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
        migrations.RemoveField(
            model_name='gadmboundary',
            name='geometry',
        ),
        migrations.AddField(
            model_name='gadmboundary',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
        migrations.RemoveField(
            model_name='worldbankboundary',
            name='geometry',
        ),
        migrations.AddField(
            model_name='worldbankboundary',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
