# Generated by Django 5.2.7 on 2025-12-23 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_alter_continent_geometry_alter_gadmboundary_geometry_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GadmBoundary',
        ),
    ]
