# Generated by Django 5.2.7 on 2025-12-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_delete_gadmboundary'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldBankRegionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_adm1_code', models.CharField(max_length=50, unique=True)),
                ('country_code', models.CharField(max_length=2)),
                ('wb_region_code', models.CharField(max_length=10)),
                ('wb_region_name', models.CharField(max_length=255)),
                ('iso_region_name', models.CharField(blank=True, max_length=255, null=True)),
                ('iso_region_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
