# Generated by Django 5.2.7 on 2025-12-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0009_importtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldbankboundary',
            name='iso_code',
        ),
        migrations.RemoveField(
            model_name='worldbankboundary',
            name='name',
        ),
        migrations.AddField(
            model_name='worldbankboundary',
            name='adm1_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worldbankboundary',
            name='adm1_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='worldbankboundary',
            name='adm2_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worldbankboundary',
            name='adm2_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='worldbankboundary',
            name='iso_a2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
