# Generated by Django 5.2.7 on 2025-12-23 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0010_remove_worldbankboundary_iso_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoKlikEpoch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 2025.1', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeoKlikRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_a2', models.CharField(max_length=2)),
                ('adm1_code', models.CharField(max_length=50)),
                ('min_lat', models.FloatField()),
                ('max_lat', models.FloatField()),
                ('min_lon', models.FloatField()),
                ('max_lon', models.FloatField()),
                ('is_giant', models.BooleanField(default=False, help_text='Area > 456,976 km2')),
                ('epoch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='geo.geoklikepoch')),
            ],
            options={
                'unique_together': {('epoch', 'adm1_code')},
            },
        ),
    ]
